# site settings
title: bcbrian
subtitle: rapid app prototyping
email: me@bcbrian.com
description: A blog about getting apps up and going quickly
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcbrian-blog.netlify.com" # the base hostname & protocol for your site
author: Brian Bartholomew
street_address: 510 Lovell Ave #8 
city: Roseville
state: MN
zip_code: 55113
country: United States of America
phone: (801) 200-2978

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/bcbrian
gitlab_url: https://gitlab.com/u/bcbrian
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/bcbrian
pinterest_url:
slack_url:
twitter_url: https://twitter.com/thebcbrian

# build settings
markdown: kramdown

sass:
  style: compressed
